#!/bin/bash -ex
unamestr=`uname`

if [[ "$unamestr" == 'Darwin' ]]; then
   brew install elixir node yarn
elif [[ "$unamestr" == 'Linux' ]]; then
	if [[ -n "$(command -v yum)" ]]; then
		sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
		curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
		sudo yum install elixir yarn
	elif [[ -n "$(command -v apt-get)" ]]; then
		wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
		curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
		curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
		echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
		sudo apt-get install elixir nodejs yarn
	fi
fi

if [[ "$packageManager" == 'unknown' ]]; then
	echo "Couldn't reliably ascern OS package manager please view source to see what script is trying to do"
else
	mix local.hex --force
	mix deps.get

	yarn install
fi
